spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/handsondb/account;AUTO_SERVER=TRUE   # 여러 Application 들이 같은 DB서버를 바라볼 수 있다! (단 항상 켜져있어서 필요할 때 리셋해줘야함. 써버 끌때 파일 지우는 거 구현하면 해결될듯)
    username: sa
    password: sa
  jpa:
    show-sql: true
  flyway:
    locations: ["classpath:db/migration", "classpath:db/sample-data"]

server:
  port: 0
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.web: debug
