spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/handsondb/article;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    show-sql: true
  flyway:
    locations: ["classpath:db/migration", "classpath:db/sample-data"]

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.web: debug
